// THIS FILE IS AUTOGENERATED BY RETRO DEV (v0.0.19).

module.exports = {
	"version": "0.0.19",
	"command": {
		"cached": false,
		"source_map": true,
		"port": 8000
	},
	"dir_config": {
		"asset_dir": "public",
		"pages_dir": "src/pages",
		"cache_dir": "__cache__",
		"build_dir": "export"
	},
	"base_page": "\u003c!DOCTYPE html\u003e\n\u003chtml lang=\"en\"\u003e\n\t\u003chead\u003e\n\t\t\u003cmeta charset=\"utf-8\" /\u003e\n\t\t\u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /\u003e\n\t\t%head%\n\t\u003c/head\u003e\n\t\u003cbody\u003e\n\t\t%page%\n\t\u003c/body\u003e\n\u003c/html\u003e\n",
	"page_based_router": [
		{
			"src_path": "src/pages/bulbasaur.js",
			"dst_path": "export/bulbasaur.html",
			"path": "/bulbasaur",
			"component": "PageBulbasaur"
		},
		{
			"src_path": "src/pages/charmander.js",
			"dst_path": "export/charmander.html",
			"path": "/charmander",
			"component": "PageCharmander"
		},
		{
			"src_path": "src/pages/index.js",
			"dst_path": "export/index.html",
			"path": "/",
			"component": "PageIndex"
		},
		{
			"src_path": "src/pages/pikachu.js",
			"dst_path": "export/pikachu.html",
			"path": "/pikachu",
			"component": "PagePikachu"
		},
		{
			"src_path": "src/pages/squirtle.js",
			"dst_path": "export/squirtle.html",
			"path": "/squirtle",
			"component": "PageSquirtle"
		}
	]
}
