import conf from "./conf"
import fs from "fs"
import path from "path"
import { getPageSrcs } from "./utils"
import { parseRouteInfo } from "../Router/parts"

const srcs = getPageSrcs()
const routeInfos = srcs.map(each => path.parse(each).name).map(each => parseRouteInfo("/" + each))

// TODO: Change to `ReactDOM.hydrate`.
// TODO: Add support for `React.StrictMode`?
// TODO: Add support for `<App>` wrapper component.
function run() {
	// prettier-ignore
	const app = `
// THIS FILE IS AUTOGENERATED.
// THESE AREN’T THE FILES YOU’RE LOOKING FOR. MOVE ALONG.

import React from "react"
import ReactDOM from "react-dom"
import { Route, Router } from "./Router"

// Pages
${routeInfos.map(each => `import ${each!.component} from ${JSON.stringify("." + each!.page)}`).join("\n")}

// Page props
import pageProps from "./pageProps"

export default function App() {
	return (
		<Router>
			${routeInfos.map(each => `
			<Route page=${JSON.stringify(each!.page)}>
				<${each!.component} {...pageProps.${each!.component}} />
			</Route>
`).join("")}
		</Router>
	)
}

ReactDOM.render(
	<App />,
	document.getElementById("root"),
)
`.trim()
	fs.writeFileSync(conf.CACHE_DIR + "/app.js", app + "\n")
}

;(() => {
	run()
})()
