package retro

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	p "path"
	"strings"
	"time"

	"github.com/zaydek/retro/pkg/loggers"
	"github.com/zaydek/retro/pkg/perm"
)

// type srvResponse struct {
// 	Hints    []api.Message `json:"hints"`
// 	Warnings []api.Message `json:"warnings"`
// 	Errors   []api.Message `json:"errors"`
// }

func emitRuntime(runtime Runtime) error {
	bstr, err := json.MarshalIndent(runtime, "", "\t")
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.Write([]byte("// THIS FILE IS AUTOGENERATED BY RETRO " + strings.ToUpper(runtime.getCmdName()) + " (v" + runtime.Version + ")."))
	buf.Write([]byte("\n"))
	buf.Write([]byte("\n"))
	buf.Write([]byte("module.exports = "))
	buf.Write(bstr)
	buf.Write([]byte("\n")) // EOF

	dst := p.Join(runtime.DirConfiguration.CacheDirectory, "runtime.js")
	if err := ioutil.WriteFile(dst, buf.Bytes(), perm.File); err != nil {
		return err
	}
	return nil
}

func (r Runtime) Dev() {
	if err := emitRuntime(r); err != nil {
		loggers.ErrorAndEnd("An unexpected error occurred.\n\n" +
			err.Error())
	}
	// ...
}

func (r Runtime) Export() {
	if err := copyAssetDirToBuildDir(r.DirConfiguration); err != nil {
		loggers.ErrorAndEnd("An unexpected error occurred.\n\n" +
			err.Error())
	}
	fmt.Println("TODO")
}

func (r Runtime) Serve() {
	if _, err := os.Stat(r.DirConfiguration.BuildDirectory); os.IsNotExist(err) {
		loggers.ErrorAndEnd("It looks like you’re trying to run retro serve but you haven’t run retro export yet. " +
			"Try retro export && retro serve.")
	}

	go func() {
		time.Sleep(100 * time.Millisecond)
		loggers.OK(fmt.Sprintf("http://localhost:%s", r.getPort()))
	}()

	// fs := http.FileServer(http.Dir(r.DirConfiguration.BuildDirectory))
	// http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	// 	if p.Ext(r.URL.Path) == "" {
	// 		r.URL.Path += ".html"
	// 	}
	// 	fs.ServeHTTP(w, r)
	// })
	// must(http.ListenAndServe(":"+r.getPort(), nil))
	must(http.ListenAndServe(":"+r.getPort(), http.FileServer(http.Dir(r.DirConfiguration.BuildDirectory))))
}
