export const none          = (...args: unknown[]): string => args.join(" ")
export const bold          = (...args: unknown[]): string => `\x1b[0;1m${args.join(" ")}\x1b[0m`
export const gray          = (...args: unknown[]): string => `\x1b[0;2m${args.join(" ")}\x1b[0m`
export const underline     = (...args: unknown[]): string => `\x1b[0;4m${args.join(" ")}\x1b[0m`
export const black         = (...args: unknown[]): string => `\x1b[0;30m${args.join(" ")}\x1b[0m`
export const red           = (...args: unknown[]): string => `\x1b[0;31m${args.join(" ")}\x1b[0m`
export const green         = (...args: unknown[]): string => `\x1b[0;32m${args.join(" ")}\x1b[0m`
export const yellow        = (...args: unknown[]): string => `\x1b[0;33m${args.join(" ")}\x1b[0m`
export const purple        = (...args: unknown[]): string => `\x1b[0;34m${args.join(" ")}\x1b[0m`
export const magenta       = (...args: unknown[]): string => `\x1b[0;35m${args.join(" ")}\x1b[0m`
export const teal          = (...args: unknown[]): string => `\x1b[0;36m${args.join(" ")}\x1b[0m`
export const white         = (...args: unknown[]): string => `\x1b[0;37m${args.join(" ")}\x1b[0m`
export const boldUnderline = (...args: unknown[]): string => `\x1b[1;4m${args.join(" ")}\x1b[0m`
export const boldBlack     = (...args: unknown[]): string => `\x1b[1;30m${args.join(" ")}\x1b[0m`
export const boldRed       = (...args: unknown[]): string => `\x1b[1;31m${args.join(" ")}\x1b[0m`
export const boldGreen     = (...args: unknown[]): string => `\x1b[1;32m${args.join(" ")}\x1b[0m`
export const boldYellow    = (...args: unknown[]): string => `\x1b[1;33m${args.join(" ")}\x1b[0m`
export const boldPurple    = (...args: unknown[]): string => `\x1b[1;34m${args.join(" ")}\x1b[0m`
export const boldMagenta   = (...args: unknown[]): string => `\x1b[1;35m${args.join(" ")}\x1b[0m`
export const boldTeal      = (...args: unknown[]): string => `\x1b[1;36m${args.join(" ")}\x1b[0m`
export const boldWhite     = (...args: unknown[]): string => `\x1b[1;37m${args.join(" ")}\x1b[0m`
