import conf from "./conf"
import fs from "fs"
import path from "path"
import { getPageSrcs, serverGuards } from "./utils"
import { parseRoutes } from "../Router/parts"

// prettier-ignore
interface PageProps {
	component: string
	props:     any
}

type PagePropsMap = {
	[key: string]: PageProps
}

// Prerenders props on the server.
async function asyncRun() {
	serverGuards()

	const propPromises = []

	// Asynchronously prerender page props.
	const srcs = getPageSrcs()
	for (const src of srcs) {
		const promise = new Promise<PageProps>(async resolve => {
			const basename = path.parse(src).name
			const routes = parseRoutes("/" + basename)
			if (routes === null) {
				throw new Error(`prerender-props: parseRoutes(${JSON.stringify(basename)})`)
			}

			// TODO: Rename to `props` and add support for `pages`; `pages` needs to
			// pass props to `head`.
			const { load } = require("../" + conf.PAGES_DIR + "/" + src) // FIXME: Change `/` for COMPAT
			let props = null
			if (load) {
				props = await load()
			}
			resolve({ component: routes.page, props })
		})
		propPromises.push(promise)
	}

	// Reduce from an array to a map:
	const propsArr = await Promise.all(propPromises)
	const propsMap = propsArr.reduce((acc, each) => {
		acc[each.component] = each.props
		return acc
	}, {} as PagePropsMap)

	const out = `
// THIS FILE IS AUTOGENERATED.
// THESE AREN’T THE FILES YOU’RE LOOKING FOR. MOVE ALONG.

module.exports = ${JSON.stringify(propsMap, null, "\t")}
`.trim()

	fs.writeFileSync(conf.CACHE_DIR + "/pageProps.js", out + "\n") // FIXME: Change `/` for COMPAT
}

;(async () => {
	await asyncRun()
})()
